{"name": "test_repeated_corier_creation_failed_message", "status": "failed", "statusDetails": {"message": "AssertionError: assert '{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}' == {'message': 'Этот логин уже используется'}\n +  where '{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}' = <Response [409]>.text", "trace": "self = <tests.test_courier_creation.TestCourierCreation object at 0x00000245D1F50B30>\n\n    @allure.description('Проверка тела ответа (сообщения) при запросе на ручку создания курьера с указанем в теле данных ранее созданного курьера')\n    def test_repeated_corier_creation_failed_message(self):\n        courier_creation_request = ScooterApi.courier_creation(DataBodies.CREATED_COURIER)\n>       assert courier_creation_request.text == {\"message\": \"Этот логин уже используется\"}\nE       assert '{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}' == {'message': 'Этот логин уже используется'}\nE        +  where '{\"code\":409,\"message\":\"Этот логин уже используется. Попробуйте другой.\"}' = <Response [409]>.text\n\ntests\\test_courier_creation.py:31: AssertionError"}, "description": "Проверка тела ответа (сообщения) при запросе на ручку создания курьера с указанем в теле данных ранее созданного курьера", "start": 1725817626093, "stop": 1725817626361, "uuid": "23439057-b93d-40ea-a11a-821938222df8", "historyId": "b504cd525646cf743b03103eca8ae06a", "testCaseId": "b504cd525646cf743b03103eca8ae06a", "fullName": "tests.test_courier_creation.TestCourierCreation#test_repeated_corier_creation_failed_message", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "mr_cat"}, {"name": "thread", "value": "17924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}